### ISSUE TITLE
Unselecting option for multiple select is not working

### ISSUE THREAD

**Issue by eLFuvo** [AuHau/select-picker#14] opened 2018-11-28 11:27 UTC
- jQuery: 3.2.1
- Select Picker: 0.3.2

When I remove item from selected options (i.e. "tag" from "tags" list) then option in select node is not unselecting.

This must be fixed by properly unselecting option in picker.js:183

```JavaScript
this.$elem.find("option[value='" + selectedId + "']").prop("selected", false);
```

**Comment by AuHau** [comment] 2018-12-06 02:21
So I have finally found some time to look at this, but to be honest I am not sure what is wrong. I checked my documentation website regarding this behavior but everything seems in order when comes to `selected` attribute adding/removing.

Can you please provide JSFiddle example with the replicated bug?

Also, I don't think that your proposed change of using `prop()` instead `attr()`/`removeAttr()` actually effects anything.

**Comment by eLFuvo** [comment] 2018-12-08 07:45
I'm using custom plugin that dinamycaly loads options for select.
That plugin sets pre-defined selected options.

By [W3C](https://www.w3schools.com/tags/att_option_selected.asp) selected attribute must be set like this:
```html
<option value="" selected>Selected option</option>
```
So that plugin sets this property properly (like above).
Every time when selects is changed I'm render its again and its does look as must.

**Comment by AuHau** [comment] 2018-12-08 07:59
First of all, I would be careful using a W3CSchools as a reference. That site is well-known not to be the best source of information. One good source for reference is for example [developer.mozilla.org](https://developer.mozilla.org).

But to come to the point, boolean attributes (such as `selected`) have several ways how they can be written. One of them is as you said just `selected`, but another as much same valid option is `selected='selected'` ([link to specification](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes)), therefore your proposed change does not effects the functionality on HTML5 level.

Soooo, I am not still so sure what is the problem. Can you provide JSFiddle with replicated bug? I am starting to think that the problem might be in the "custom plugin" part...

**Comment by eLFuvo** [comment] 2018-12-09 12:48
I've open that project and adapt those bug for showing
https://jsfiddle.net/fgb4zuey/27/

PS: W3C approves standards to be observed by browser makers, including Mozilla

**Comment by AuHau** [comment] 2018-12-10 01:35
Hmm, now I can see what are you trying to achieve. I am afraid it is not possible with the approach you are using. 

You can't directly manipulate the underlying select element and expect that the changes will be directly propagated to the `picker` instance. Picker does not support this. In order to achieve what you want, you have to use the picker's API (eq. `$elem.picker('set', id)` and `$elem.picker('remove', id)`). 

If you want to write support for such a use-case, PR will be welcomed. But from my perspective, this is not a bug but a feature request and a one that I am not planning to implement (for me select-picker is in maintenance mode and I don't really plan to work on any new features, only fixes), hence I am closing this.

PS: Yes W3C is a standardization body, but W3C**School** is not related to it in any way except the name. See: https://www.w3schools.com/about/

**Closed as completed by AuHau** 2018-12-10 01:35 UTC
